# Generated by Django 3.2.3 on 2021-06-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=500)),
                ('prod_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('Category', models.CharField(max_length=500)),
                ('Description', models.TextField()),
                ('prod_img', models.CharField(max_length=1000)),
            ],
        ),
    ]
