# Generated by Django 3.2.3 on 2021-06-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myshop', '0003_auto_20210612_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
