# Generated by Django 3.2.3 on 2021-06-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myshop', '0004_orders_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Instock',
            field=models.BooleanField(default=True, verbose_name=True),
            preserve_default=False,
        ),
    ]
